// Generated by build_deck.py — do not edit by hand.
window.ANKI = {
 "themes": [
  {
   "id": "investing",
   "label": "Investing"
  },
  {
   "id": "work",
   "label": "Work"
  },
  {
   "id": "ideas",
   "label": "Ideas"
  },
  {
   "id": "mindfulness",
   "label": "Mindfulness"
  }
 ],
 "books": [
  {
   "id": "expectations-investing-reading-stock-prices-for-better-returns-revised-and-updat--michael-j-mauboussin",
   "title": "Expectations Investing: Reading Stock Prices for Better Returns, Revised and Updated (Heilbrunn Center for Graham & Dodd Investing Series)",
   "author": "Michael J. Mauboussin",
   "subject": "reading market expectations embedded in stock prices to make better investment decisions",
   "total": 5,
   "highlights": [
    {
     "id": "6215255265d13d2c",
     "loc": 60,
     "theme": "investing",
     "text": "As someone who has worked in the valuation trenches for a long time, the book reframed the question of what a company is worth, from estimating value, given fundamentals, to backing out the fundamentals that are embedded in the market price.",
     "q": "How does the book reframe the question of what a company is worth?"
    },
    {
     "id": "4c366648fc52f71f",
     "loc": 63,
     "theme": "investing",
     "text": "The first is that it cements the link between fundamentals and value by linking what the market is paying for a company to what has to happen, in terms of operating success, for that price to be justified, and makes it easier to act on those assessments. The second is that it forces valuation down to the basics, since as Al and Michael show with their parsimonious models, there are only a few levers that drive value.",
     "q": "What are the two benefits of linking market price to the operating success required to justify it?"
    },
    {
     "id": "366a2186ed22352a",
     "loc": 68,
     "theme": "investing",
     "text": "The section that goes beyond discounted cash flow valuation to look at real options is a must-read for investors and analysts, since it provides not only a tool that can be used to augment intrinsic value but also practical ways of using it. While the Domino’s Pizza example is an excellent illustration of the power of expectations investing in traditional value frameworks, the Shopify case study in the real options chapter can be a game changer if you are wondering how you should be valuing technology companies.",
     "q": "What tool does the book recommend to augment intrinsic value for valuing technology companies?"
    },
    {
     "id": "34e88a31fb1ef136",
     "loc": 76,
     "theme": "investing",
     "text": "Stock prices are a treasure of information about the market’s expectations of a company’s future performance. Investors who properly read market expectations and anticipate revisions increase their odds of achieving superior investment results.",
     "q": "According to the book, what do stock prices reveal, and what must investors do to achieve superior results?"
    },
    {
     "id": "86067c91d4b27164",
     "loc": 165,
     "theme": "investing",
     "text": "The key to successful investing is to estimate the level of expected performance embedded in the current stock price and then assess the likelihood of a revision in expectations.",
     "q": "What does the book identify as the key to successful investing?"
    }
   ]
  },
  {
   "id": "meditations-for-mortals-four-weeks-to-embrace-your-limitations-and-make-time-for--oliver-burkeman",
   "title": "Meditations for Mortals: Four Weeks to Embrace Your Limitations and Make Time for What Counts",
   "author": "Oliver Burkeman",
   "subject": "embracing human finitude and limitation to live and use time more meaningfully",
   "total": 18,
   "highlights": [
    {
     "id": "cba7f3444cfcc53d",
     "loc": 34,
     "theme": "mindfulness",
     "text": "This is a book about how the world opens up once you realize you’re never going to sort your life out.",
     "q": "According to Burkeman, what does the world do once you realize you're never going to sort your life out?"
    },
    {
     "id": "1609d5bc8c42304d",
     "loc": 35,
     "theme": "mindfulness",
     "text": "This is a book about how the world opens up once you realize you’re never going to sort your life out."
    },
    {
     "id": "757da6f62b5f518c",
     "loc": 40,
     "theme": "mindfulness",
     "text": "In short: it’s about what changes once you grasp that life as a limited human being – in an era of infinite tasks and opportunities, facing an unknowable future, alongside other humans who stubbornly insist on having their own personalities – isn’t a problem you’ve got to try to solve.",
     "q": "What is the central reframe Burkeman offers about living as a limited human in an era of infinite tasks?"
    },
    {
     "id": "249c449705905e52",
     "loc": 233,
     "theme": "mindfulness",
     "text": "Because our problem, it turns out, was never that we hadn’t yet found the right way to achieve control over life, or safety from life. Our real problem was imagining that any of that might be possible in the first place for finite humans, who, after all, just find themselves unavoidably in life, with all the limitations and feelings of claustrophobia and lack of escape routes that entails.",
     "q": "According to Burkeman, what was our real problem regarding control over life?"
    },
    {
     "id": "642387f284d9a07e",
     "loc": 236,
     "theme": "mindfulness",
     "text": "Our suffering,’ as Mel Weitsman, another Zen teacher, puts it, ‘is believing there’s a way out.’)",
     "q": "How does Zen teacher Mel Weitsman define our suffering?"
    },
    {
     "id": "3ac4e26b8c14cadf",
     "loc": 274,
     "theme": "mindfulness",
     "text": "To be human, according to this analogy, is to occupy a little one-person kayak, borne along on the river of time towards your inevitable yet unpredictable death. It’s a thrilling situation, but also an intensely vulnerable one: you’re at the mercy of the current, and all you can really do is to stay alert, steering as best you can, reacting as wisely and gracefully as possible to whatever arises from moment to moment."
    },
    {
     "id": "554203c827107575",
     "loc": 277,
     "theme": "ideas",
     "text": "The German philosopher Martin Heidegger described this state of affairs using the word Geworfenheit, or ‘thrownness,’ a suitably awkward word for an awkward predicament: merely to come into existence is to find oneself thrown into a time and place you didn’t choose, with a personality you didn’t pick, and with your time flowing away beneath you, minute by minute, whether you like it or not.",
     "q": "What does Heidegger's term Geworfenheit, or 'thrownness,' describe?"
    },
    {
     "id": "1c21660c8d7674b6",
     "loc": 282,
     "theme": "mindfulness",
     "text": "To be human, according to this analogy, is to occupy a little one-person kayak, borne along on the river of time towards your inevitable yet unpredictable death. It’s a thrilling situation, but also an intensely vulnerable one: you’re at the mercy of the current, and all you can really do is to stay alert, steering as best you can, reacting as wisely and gracefully as possible to whatever arises from moment to moment."
    },
    {
     "id": "cd44e3feb722cf60",
     "loc": 285,
     "theme": "ideas",
     "text": "The German philosopher Martin Heidegger described this state of affairs using the word Geworfenheit, or ‘thrownness,’ a suitably awkward word for an awkward predicament: merely to come into existence is to find oneself thrown into a time and place you didn’t choose, with a personality you didn’t pick, and with your time flowing away beneath you, minute by minute, whether you like it or not."
    },
    {
     "id": "a85a60826727cf78",
     "loc": 288,
     "theme": "mindfulness",
     "text": "The challenge, then, is simple, though for many of us also excruciating: What’s one thing you could do today – or tomorrow at the latest, if you’re reading this at night – that would constitute a good-enough use of a chunk of your finite time, and that you’d actually be willing to do?",
     "q": "What single question does Burkeman pose as the challenge for making good-enough use of your finite time?"
    },
    {
     "id": "57b951d0408fed29",
     "loc": 297,
     "theme": "mindfulness",
     "text": "The challenge, then, is simple, though for many of us also excruciating: What’s one thing you could do today – or tomorrow at the latest, if you’re reading this at night – that would constitute a good-enough use of a chunk of your finite time, and that you’d actually be willing to do?"
    },
    {
     "id": "73ffa3ba552666a8",
     "loc": 325,
     "theme": "ideas",
     "text": "The astounding reality – in the words of Sheldon B. Kopp, a genial and brilliant American psychotherapist who died in 1999 – is that you’re pretty much free to do whatever you like. You need only face the consequences.",
     "q": "What does Sheldon Kopp say is the astounding reality about your freedom to act?"
    },
    {
     "id": "7ba1e037839675d9",
     "loc": 330,
     "theme": "ideas",
     "text": "Freedom isn’t a matter of somehow wriggling free of the costs of your choice – that’s never an option – but of realizing, as Kopp points out, that nothing stops you doing anything at all, so long as you’re willing to pay those costs.",
     "q": "How does Kopp reframe what freedom actually is?"
    },
    {
     "id": "c03c457eec730c71",
     "loc": 334,
     "theme": "ideas",
     "text": "The conservative American economist Thomas Sowell summed things up with a bleakness I appreciate, insisting that there are no solutions, only trade-offs. The only two questions, at any moment of choice in life, is what the price is, and whether or not it’s worth paying.",
     "q": "What does Thomas Sowell claim exists instead of solutions, and what two questions matter at any moment of choice?"
    },
    {
     "id": "66f16444a1d200e3",
     "loc": 335,
     "theme": "ideas",
     "text": "The astounding reality – in the words of Sheldon B. Kopp, a genial and brilliant American psychotherapist who died in 1999 – is that you’re pretty much free to do whatever you like. You need only face the consequences."
    },
    {
     "id": "bcf481011aa8f897",
     "loc": 340,
     "theme": "ideas",
     "text": "Freedom isn’t a matter of somehow wriggling free of the costs of your choice – that’s never an option – but of realizing, as Kopp points out, that nothing stops you doing anything at all, so long as you’re willing to pay those costs."
    },
    {
     "id": "45d7546a673afe0a",
     "loc": 345,
     "theme": "ideas",
     "text": "The conservative American economist Thomas Sowell summed things up with a bleakness I appreciate, insisting that there are no solutions, only trade-offs. The only two questions, at any moment of choice in life, is what the price is, and whether or not it’s worth paying."
    }
   ]
  },
  {
   "id": "moneyball-the-art-of-winning-an-unfair-game--michael-lewis",
   "title": "Moneyball: The Art of Winning an Unfair Game",
   "author": "Michael Lewis",
   "subject": "how the Oakland A's used statistical analysis to exploit market inefficiencies in valuing baseball players",
   "total": 1,
   "highlights": [
    {
     "id": "a36ee9ca9d4f08a2",
     "loc": 173,
     "theme": "work",
     "text": "that was because it was 1980. The risks in drafting baseball players had just risen. A few years earlier, professional baseball players had been granted free agency by a court of law, and, after about two seconds of foot-shuffling, baseball owners put prices on players that defied the old commonsensical notions of what a baseball player should be paid. Inside of four years, the average big league salary had nearly tripled, from about $52,000 to almost $150,000 a year.",
     "q": "How did the introduction of free agency in the late 1970s affect big league baseball salaries within four years?"
    }
   ]
  },
  {
   "id": "the-almanack-of-naval-ravikant-a-guide-to-wealth-and-happiness--eric-jorgenson-jack-butcher-and-tim-ferriss",
   "title": "The Almanack of Naval Ravikant: A Guide to Wealth and Happiness",
   "author": "Eric Jorgenson, Jack Butcher, and Tim Ferriss",
   "subject": "how to build wealth and find happiness through leverage, judgment, and mental clarity",
   "total": 14,
   "highlights": [
    {
     "id": "1bff8c717b42a20a",
     "loc": 227,
     "theme": "work",
     "text": "Pick business partners with high intelligence, energy, and, above all, integrity.",
     "q": "What three qualities does Naval say to look for in business partners?"
    },
    {
     "id": "04502cbd23cbc1df",
     "loc": 230,
     "theme": "work",
     "text": "Learn to sell. Learn to build. If you can do both, you will be unstoppable.",
     "q": "Which two skills does Naval say make you unstoppable?"
    },
    {
     "id": "f40cf69bc6503111",
     "loc": 260,
     "theme": "ideas",
     "text": "Study microeconomics, game theory, psychology, persuasion, ethics, mathematics, and computers.",
     "q": "Which subjects does Naval recommend studying?"
    },
    {
     "id": "7f357078522a607c",
     "loc": 264,
     "theme": "work",
     "text": "Set and enforce an aspirational personal hourly rate. If fixing a problem will save less than your hourly rate, ignore it. If outsourcing a task will cost less than your hourly rate, outsource it.",
     "q": "How does Naval say to use an aspirational personal hourly rate to decide what to do or outsource?"
    },
    {
     "id": "fc01a04e9adb7417",
     "loc": 266,
     "theme": "work",
     "text": "Work as hard as you can. Even though who you work with and what you work on are more important than how hard you work.",
     "q": "According to Naval, how does working hard rank against who you work with and what you work on?"
    }
   ]
  },
  {
   "id": "the-beginning-of-infinity-explanations-that-transform-the-world--david-deutsch",
   "title": "The Beginning of Infinity: Explanations That Transform the World",
   "author": "David Deutsch",
   "subject": "how the pursuit of good explanations drives unbounded scientific and human progress",
   "total": 3,
   "highlights": [
    {
     "id": "804821ac6d45a8d7",
     "loc": 64,
     "theme": "ideas",
     "text": "Progress that is both rapid enough to be noticed and stable enough to continue over many generations has been achieved only once in the history of our species. It began at approximately the time of the scientific revolution, and is still under way.",
     "q": "According to Deutsch, when did progress rapid enough to notice and stable enough to continue across generations begin?"
    },
    {
     "id": "35668b7ca41b0820",
     "loc": 71,
     "theme": "ideas",
     "text": "In this book I argue that all progress, both theoretical and practical, has resulted from a single human activity: the quest for what I call good explanations.",
     "q": "What single human activity does Deutsch argue all theoretical and practical progress has resulted from?"
    },
    {
     "id": "b7d67bccfc6ed168",
     "loc": 72,
     "theme": "ideas",
     "text": "Though this quest is uniquely human, its effectiveness is also a fundamental fact about reality at the most impersonal, cosmic level – namely that it conforms to universal laws of nature that are indeed good explanations. This simple relationship between the cosmic and the human is a hint of a central role of people in the cosmic scheme of things.",
     "q": "What does Deutsch say the fact that reality conforms to universal laws that are good explanations hints about people's role in the cosmos?"
    }
   ]
  },
  {
   "id": "the-laws-of-trading-a-trader-s-guide-to-better-decision-making-for-everyone-wile--agustin-lebron",
   "title": "The Laws of Trading: A Trader's Guide to Better Decision-Making for Everyone (Wiley Trading)",
   "author": "Agustin Lebron",
   "subject": "how to make better trading decisions using principles from economics, decision theory, and market microstructure",
   "total": 2,
   "highlights": [
    {
     "id": "9686f2cd1aff25ec",
     "loc": 5208,
     "theme": "investing",
     "text": "Perhaps counterintuitively, it turns out the best place to look is at the end. What this means is that you first want to answer the question “What is the output of the process I'm building?” In the case of a trading operation, the result of the process is a strategy that does trades. The data exhaust of this process is, directly, information about orders and trades. Thus, information about past orders and trades is the most valuable sort of information you can provide to the process. This feedback-like idea is so universal that it manages to rise to the level of a general principle. The most valuable data as inputs to a process are past outputs of the same (or sufficiently similar) processes.",
     "q": "According to Lebron, what are the most valuable data inputs to a process?"
    },
    {
     "id": "90186f93450d05c0",
     "loc": 5222,
     "theme": "investing",
     "text": "The question of what data to look for embodies a notion of locality: what is most relevant for A is information that is causally local (in the sense of proximal, or close) to A.",
     "q": "What notion of locality governs which data is most relevant to a decision A?"
    }
   ]
  },
  {
   "id": "working-backwards-insights-stories-and-secrets-from-inside-amazon--colin-bryar-and-bill-carr",
   "title": "Working Backwards: Insights, Stories, and Secrets from Inside Amazon",
   "author": "Colin Bryar and Bill Carr",
   "subject": "Amazon's internal management processes and the Working Backwards approach to building products",
   "total": 11,
   "highlights": [
    {
     "id": "ce47ecf12002bd62",
     "loc": 1411,
     "theme": "work",
     "text": "“The eerie silence in the first 20 minutes of many meetings.” At Amazon, after a brief exchange of greetings and chitchat, everyone sits at the table, and the room goes completely silent. Silent, as in not a word. The reason for the silence? A six-page document that everyone must read before discussion begins.",
     "q": "Why do Amazon meetings begin with 20 minutes of complete silence?"
    },
    {
     "id": "418ad14dce746d27",
     "loc": 1775,
     "theme": "work",
     "text": "In the end, what turned out to work best was relying on the core Amazon principle of customer obsession and a simple yet flexible way of writing narrative documents."
    },
    {
     "id": "6ec2b5ed24023bd8",
     "loc": 1887,
     "theme": "work",
     "text": "Over time, we refined and normalized the specifications for the PR/FAQ. The press release (PR) portion is a few paragraphs, always less than one page. The frequently asked questions (FAQ) should be five pages or less. There are no awards for extra pages or more words.",
     "q": "What are the length specifications for Amazon's PR/FAQ document?"
    },
    {
     "id": "75e361e0a70ea8c7",
     "loc": 2736,
     "theme": "ideas",
     "text": "But as Steve explained Jeff’s thinking, I began to feel differently. Jeff, Steve told me, had decided that Amazon was at an important crossroads, and now was the time to act. Though the physical media business was growing, we all understood that over time it would decline in popularity and importance as the media business shifted to digital."
    },
    {
     "id": "b45af13100f04e26",
     "loc": 2791,
     "theme": "work",
     "text": "In other words, his first action was not a “what” decision, it was a “who” and “how” decision. This is an incredibly important difference. Jeff did not jump straight to focusing on what product to build, which seems like the straightest line from A to B. Instead, the choices he made suggest he believed that the scale of the opportunity was large and that the scope of the work required to achieve success was equally large and complex. He focused first on how to organize the team and who was the right leader to achieve the right result.",
     "q": "According to the authors, what kind of decision did Jeff make first—rather than jumping to a 'what' decision about which product to build?"
    },
    {
     "id": "7e355c9dce59b69c",
     "loc": 2821,
     "theme": "work",
     "text": "For this to become one of Amazon’s biggest and most important businesses, Jeff needed Steve, an experienced and proven vice president (now promoted to senior vice president), reporting to Jeff, single-threaded on digital. Steve would in turn need to build a team of senior leaders under him, each of whom would be single-threaded on one aspect of the business, such as device hardware, e-books, music, or video.",
     "q": "What does it mean for a leader or team to be 'single-threaded' at Amazon?"
    },
    {
     "id": "af169f2c4568067f",
     "loc": 2852,
     "theme": "ideas",
     "text": "He would frequently describe the two fundamental approaches that each company must choose between when developing new products and services. We could be a fast follower—that is, make a close copy of successful products that other companies had built—or we could invent a new product on behalf of our customers. He said that either approach is valid, but he wanted Amazon to be a company that invents.",
     "q": "What two fundamental approaches to developing products does Bezos describe, and which did he want Amazon to pursue?"
    },
    {
     "id": "30ceb40d63fe779d",
     "loc": 2881,
     "theme": "work",
     "text": "It was thanks to the combination of Amazon processes, which we discussed in part one of the book, that Jeff was able to make these changes. For example, the six-page document and S-Team goals allowed Jeff to stay aligned on all major retail and marketplace programs and give feedback in an efficient manner, even as he devoted less calendar time to those businesses. And for new initiatives in Digital (as well as AWS), the PR/FAQ process enabled him to spend weeks or months to gain alignment and clarity at a high level of detail on each project."
    },
    {
     "id": "c9e65c5b2b7600cd",
     "loc": 2889,
     "theme": "work",
     "text": "On the organizational side, we used the two-pizza team structure, which allowed our Digital teams to not be dependent on or a distraction to the engineering and business teams running the retail and marketplace business. Our people were autonomous with respect to their ability to achieve the goals that they had agreed to with Jeff. From Jeff’s point of view, this meant he wouldn’t be stymied by arbitrating resource conflicts and dependencies at the ground level. He could hold each two-pizza team leader accountable for staffing their team and achieving their goals. Furthermore, he could easily audit whether an important initiative was staffed to succeed.",
     "q": "How did the two-pizza team structure benefit Jeff's oversight of Digital teams?"
    },
    {
     "id": "2c7aa36f1ac8716c",
     "loc": 2914,
     "theme": "work",
     "text": "With each modification, the scope of each leader’s responsibilities would become narrower, but the intended scale of each role was greater. At most companies, reducing a leader’s scope would be considered a demotion, and in fact there were many VPs and directors who saw each of these changes in that way. At Amazon, it was not a demotion. It was a signal that we were thinking big and investing in digital for the long term.",
     "q": "Why was narrowing a leader's scope not considered a demotion at Amazon?"
    },
    {
     "id": "dded97f63e5b1241",
     "loc": 2956,
     "theme": "work",
     "text": "In one of our meetings, he said that a typical company that wanted to grow would take stock of its existing capabilities and ask, “What can we do next with our skill set?” He emphasized that Amazon’s approach was always to start from the customer and work backwards. We would figure out what the customers’ needs were and then ask ourselves, “Do we have the skills necessary to build something that meets those needs? If not, how can we build or acquire them?” Once we determined what was necessary to create value for our customers and to differentiate ourselves from our competitors, we didn’t let our lack of ability deter us from achieving this important end result—our own device.",
     "q": "How does Amazon's 'work backwards' approach differ from how a typical company decides what to build next?"
    }
   ]
  },
  {
   "id": "you-can-be-a-stock-market-genius-uncover-the-secret-hiding-places-of-stock-marke--joel-greenblatt",
   "title": "You Can Be a Stock Market Genius: Uncover the Secret Hiding Places of Stock Market P",
   "author": "Joel Greenblatt",
   "subject": "finding investment profits in special situations like spinoffs, mergers, and other overlooked corporate events",
   "total": 9,
   "highlights": [
    {
     "id": "787420a431f5a49c",
     "loc": 66,
     "theme": "investing",
     "text": "According to Bob, the bottom line and the measure of his success is this: How does the return on his portfolio stack up against the return of the Standard & Poor’s 500 average? In fact, Bob’s record is phenomenal: over the past ten years his average annual return has exceeded the return of the S&P 500 by between 2 and 3 percent.",
     "q": "According to the book, what is the benchmark against which Bob measures his portfolio's success?"
    },
    {
     "id": "427bfd95bd0616db",
     "loc": 82,
     "theme": "investing",
     "text": "It turns out that diversification addresses only a portion (and not the major portion) of the overall risk of investing in the stock market. Even if you took the precaution of owning 9,000 stocks, you would still be at risk for the up and down movement of the entire market. This risk, known as market risk, would not have been eliminated by your “perfect” diversification. While simply buying more stocks can’t help you avoid market risk, it can help you avoid another kind of risk—“nonmarket risk.” Nonmarket risk is the portion of a stock’s risk that is not related to the stock market’s overall movements.",
     "q": "What is market risk versus nonmarket risk, and which one does diversification address?"
    },
    {
     "id": "fab391f1798efc04",
     "loc": 92,
     "theme": "investing",
     "text": "After purchasing six or eight stocks in different industries, the benefit of adding even more stocks to your portfolio in an effort to decrease risk is small, and 2. Overall market risk will not be eliminated merely by adding more stocks to your portfolio.",
     "q": "After roughly how many stocks in different industries does adding more provide little further risk reduction, and what risk still remains?"
    },
    {
     "id": "df148390a7b976f7",
     "loc": 109,
     "theme": "investing",
     "text": "they ask themselves only one question before buying. Are there comparable pieces of furniture or paintings that have recently sold at auction (or to dealers) at prices far above the potential purchase price?",
     "q": "What single question do savvy art and furniture buyers ask before purchasing?"
    },
    {
     "id": "9b9adefe13a3bc97",
     "loc": 117,
     "theme": "investing",
     "text": "Finding bargain stocks works much the same way. If you spend your energies looking for and analyzing situations not closely followed by other informed investors, your chance of finding bargains greatly increases. The trick is locating those opportunities.",
     "q": "How does focusing on situations not closely followed by other informed investors improve your chances of finding bargains?"
    },
    {
     "id": "0d3edd049949900d",
     "loc": 177,
     "theme": "investing",
     "text": "It doesn’t pay for Wall Street analysts to cover stocks or investment situations unless they can generate enough revenue (read commissions or future investment-banking fees) to make the time and effort involved worthwhile. Therefore, smaller capitalization stocks whose shares don’t trade in large volumes, obscure securities, and unique situations are generally ignored. Ironically, the very areas that are uneconomic for large firms to explore are precisely the ones that hold the most potential profit for you.",
     "q": "Why do Wall Street analysts ignore small-cap stocks and obscure situations, and why does that benefit individual investors?"
    },
    {
     "id": "b36cb9d97bfa855a",
     "loc": 200,
     "theme": "investing",
     "text": "Unfortunately, life doesn’t usually work that way. You can’t always choose your battles or your playing field. When it comes to the stock market, though, you can. This concept has been variously illustrated by the likes of Warren Buffett as “Swing at only one of twenty pitches,” “There are no called strikes on Wall Street,” or “Wait for your pitch.”",
     "q": "What Buffett metaphors capture the idea that in the stock market you can choose which opportunities to act on?"
    },
    {
     "id": "2322945992911620",
     "loc": 204,
     "theme": "investing",
     "text": "It makes sense that if you limit your investments to those situations where you are knowledgeable and confident, and only those situations, your success rate will be very high."
    },
    {
     "id": "939dba1eb61f05a5",
     "loc": 245,
     "theme": "investing",
     "text": "If you’re looking to avoid putting all your eggs in one basket, this broader type of diversification, over varying asset classes, will accomplish that goal more effectively than merely diversifying your stock portfolio. In other words, don’t screw up a perfectly good stock-market strategy by diversifying your way into mediocre returns.",
     "q": "What type of diversification does the book say more effectively avoids putting all your eggs in one basket than merely diversifying a stock portfolio?"
    }
   ]
  }
 ]
};
